<?php

return [
    // Market Stalls
    [
        "stall_category_id" => 7,
        "name" => "Stall 1",
        "is_occupied" => false,
        "coordinates" => json_encode([121.52785096661347, 13.964688164207226]),
        "location_description" => null,
        "size" => json_encode(["length" => 4.8, "width" => 7.71]),
    ],
    [
        "stall_category_id" => 7,
        "name" => "Stall 2",
        "is_occupied" => false,
        "coordinates" => json_encode([121.52782390109604, 13.965023050206746]),
        "location_description" => null,
        "size" => json_encode(["length" => 3.8, "width" => 7.17]),
    ],
    [
        "stall_category_id" => 7,
        "name" => "Stall 3",
        "is_occupied" => false,
        "coordinates" => json_encode([121.5276502306926, 13.965097469251646]),
        "location_description" => null,
        "size" => json_encode(["length" => 4.29, "width" => 7.17]),
    ],
    [
        "stall_category_id" => 7,
        "name" => "Stall 4",
        "is_occupied" => false,
        "coordinates" => json_encode([
            121.52785 + rand(-5, 5) / 1000,
            13.964688 + rand(-5, 5) / 1000,
        ]),
        "location_description" => null,
        "size" => json_encode(["length" => 3.81, "width" => 7.17]),
    ],
    [
        "stall_category_id" => 7,
        "name" => "Stall 5",
        "is_occupied" => false,
        "coordinates" => json_encode([121.52767504075022, 13.965141245149185]),
        "location_description" => null,
        "size" => json_encode(["length" => 3.83, "width" => 7.17]),
    ],
    [
        "stall_category_id" => 7,
        "name" => "Stall 6",
        "is_occupied" => false,
        "coordinates" => json_encode([
            121.52785 + rand(-5, 5) / 1000,
            13.964688 + rand(-5, 5) / 1000,
        ]),
        "location_description" => null,
        "size" => json_encode(["length" => 8.13, "width" => 7.17]),
    ],
    [
        "stall_category_id" => 7,
        "name" => "Stall 7",
        "is_occupied" => false,
        "coordinates" => json_encode([
            121.52785 + rand(-5, 5) / 1000,
            13.964688 + rand(-5, 5) / 1000,
        ]),
        "location_description" => null,
        "size" => json_encode(["length" => 4.75, "width" => 2.95]),
    ],
    [
        "stall_category_id" => 7,
        "name" => "Stall 8",
        "is_occupied" => false,
        "coordinates" => json_encode([
            121.52785 + rand(-5, 5) / 1000,
            13.964688 + rand(-5, 5) / 1000,
        ]),
        "location_description" => null,
        "size" => json_encode(["length" => 9.3, "width" => 6.72]),
    ],
    [
        "stall_category_id" => 7,
        "name" => "Stall 9",
        "is_occupied" => false,
        "coordinates" => json_encode([
            121.52785 + rand(-5, 5) / 1000,
            13.964688 + rand(-5, 5) / 1000,
        ]),
        "location_description" => null,
        "size" => json_encode(["length" => 3.32, "width" => 5.78]),
    ],
    [
        "stall_category_id" => 7,
        "name" => "Stall 10",
        "is_occupied" => false,
        "coordinates" => json_encode([
            121.52785 + rand(-5, 5) / 1000,
            13.964688 + rand(-5, 5) / 1000,
        ]),
        "location_description" => null,
        "size" => json_encode(["length" => 3.65, "width" => 4.71]),
    ],
    [
        "stall_category_id" => 7,
        "name" => "Stall 11",
        "is_occupied" => false,
        "coordinates" => json_encode([
            121.52785 + rand(-5, 5) / 1000,
            13.964688 + rand(-5, 5) / 1000,
        ]),
        "location_description" => null,
        "size" => json_encode(["length" => 5.5, "width" => 4.35]),
    ],
    [
        "stall_category_id" => 7,
        "name" => "Stall 12",
        "is_occupied" => false,
        "coordinates" => json_encode([
            121.52785 + rand(-5, 5) / 1000,
            13.964688 + rand(-5, 5) / 1000,
        ]),
        "location_description" => null,
        "size" => json_encode(["length" => 6.8, "width" => 5.95]),
    ],
    [
        "stall_category_id" => 7,
        "name" => "Stall 13",
        "is_occupied" => false,
        "coordinates" => json_encode([
            121.52785 + rand(-5, 5) / 1000,
            13.964688 + rand(-5, 5) / 1000,
        ]),
        "location_description" => null,
        "size" => json_encode(["length" => 6.16, "width" => 5.12]),
    ],
    // Table Rentals - Fish Section
    [
        "stall_category_id" => 1,
        "name" => "Table 1-Fish Section",
        "is_occupied" => false,
        "coordinates" => json_encode([
            121.52785 + rand(-5, 5) / 1000,
            13.964688 + rand(-5, 5) / 1000,
        ]),
        "location_description" => "Fish Section",
        "size" => null,
    ],
    [
        "stall_category_id" => 1,
        "name" => "Table 2-Fish Section",
        "is_occupied" => false,
        "coordinates" => json_encode([
            121.52785 + rand(-5, 5) / 1000,
            13.964688 + rand(-5, 5) / 1000,
        ]),
        "location_description" => "Fish Section",
        "size" => null,
    ],
    [
        "stall_category_id" => 1,
        "name" => "Table 3-Fish Section",
        "is_occupied" => false,
        "coordinates" => json_encode([
            121.52785 + rand(-5, 5) / 1000,
            13.964688 + rand(-5, 5) / 1000,
        ]),
        "location_description" => "Fish Section",
        "size" => null,
    ],
    [
        "stall_category_id" => 1,
        "name" => "Table 4-Fish Section",
        "is_occupied" => false,
        "coordinates" => json_encode([
            121.52785 + rand(-5, 5) / 1000,
            13.964688 + rand(-5, 5) / 1000,
        ]),
        "location_description" => "Fish Section",
        "size" => null,
    ],
    [
        "stall_category_id" => 1,
        "name" => "Table 5-Fish Section",
        "is_occupied" => false,
        "coordinates" => json_encode([
            121.52785 + rand(-5, 5) / 1000,
            13.964688 + rand(-5, 5) / 1000,
        ]),
        "location_description" => "Fish Section",
        "size" => null,
    ],
    [
        "stall_category_id" => 1,
        "name" => "Table 6-Fish Section",
        "is_occupied" => false,
        "coordinates" => json_encode([
            121.52785 + rand(-5, 5) / 1000,
            13.964688 + rand(-5, 5) / 1000,
        ]),
        "location_description" => "Fish Section",
        "size" => null,
    ],
    [
        "stall_category_id" => 1,
        "name" => "Table 7-Fish Section",
        "is_occupied" => false,
        "coordinates" => json_encode([
            121.52785 + rand(-5, 5) / 1000,
            13.964688 + rand(-5, 5) / 1000,
        ]),
        "location_description" => "Fish Section",
        "size" => null,
    ],
    [
        "stall_category_id" => 1,
        "name" => "Table 8-Fish Section",
        "is_occupied" => false,
        "coordinates" => json_encode([
            121.52785 + rand(-5, 5) / 1000,
            13.964688 + rand(-5, 5) / 1000,
        ]),
        "location_description" => "Fish Section",
        "size" => null,
    ],
    [
        "stall_category_id" => 1,
        "name" => "Table 9-Fish Section",
        "is_occupied" => false,
        "coordinates" => json_encode([
            121.52785 + rand(-5, 5) / 1000,
            13.964688 + rand(-5, 5) / 1000,
        ]),
        "location_description" => "Fish Section",
        "size" => null,
    ],
    [
        "stall_category_id" => 1,
        "name" => "Table 10-Fish Section",
        "is_occupied" => false,
        "coordinates" => json_encode([
            121.52785 + rand(-5, 5) / 1000,
            13.964688 + rand(-5, 5) / 1000,
        ]),
        "location_description" => "Fish Section",
        "size" => null,
    ],
    //Meat Table

    // Poultry
    [
        "stall_category_id" => 2,
        "name" => "Table 1-Poultry Section",
        "is_occupied" => false,
        "coordinates" => json_encode([
            121.52785 + rand(-5, 5) / 1000,
            13.964688 + rand(-5, 5) / 1000,
        ]),
        "location_description" => "Poultry Section",
        "size" => null,
    ],
    [
        "stall_category_id" => 2,
        "name" => "Table 2-Poultry Section",
        "is_occupied" => false,
        "coordinates" => json_encode([
            121.52785 + rand(-5, 5) / 1000,
            13.964688 + rand(-5, 5) / 1000,
        ]),
        "location_description" => "Poultry Section",
        "size" => null,
    ],
    [
        "stall_category_id" => 2,
        "name" => "Table 3-Poultry Section",
        "is_occupied" => false,
        "coordinates" => json_encode([
            121.52785 + rand(-5, 5) / 1000,
            13.964688 + rand(-5, 5) / 1000,
        ]),
        "location_description" => "Poultry Section",
        "size" => null,
    ],
    [
        "stall_category_id" => 2,
        "name" => "Table 4-Poultry Section",
        "is_occupied" => false,
        "coordinates" => json_encode([
            121.52785 + rand(-5, 5) / 1000,
            13.964688 + rand(-5, 5) / 1000,
        ]),
        "location_description" => "Poultry Section",
        "size" => null,
    ],
    [
        "stall_category_id" => 2,
        "name" => "Table 5-Poultry Section",
        "is_occupied" => false,
        "coordinates" => json_encode([
            121.52785 + rand(-5, 5) / 1000,
            13.964688 + rand(-5, 5) / 1000,
        ]),
        "location_description" => "Poultry Section",
        "size" => null,
    ],
    [
        "stall_category_id" => 2,
        "name" => "Table 6-Poultry Section",
        "is_occupied" => false,
        "coordinates" => json_encode([
            121.52785 + rand(-5, 5) / 1000,
            13.964688 + rand(-5, 5) / 1000,
        ]),
        "location_description" => "Poultry Section",
        "size" => null,
    ],
    [
        "stall_category_id" => 2,
        "name" => "Table 7-Poultry Section",
        "is_occupied" => false,
        "coordinates" => json_encode([
            121.52785 + rand(-5, 5) / 1000,
            13.964688 + rand(-5, 5) / 1000,
        ]),
        "location_description" => "Poultry Section",
        "size" => null,
    ],
    [
        "stall_category_id" => 2,
        "name" => "Table 8-Poultry Section",
        "is_occupied" => false,
        "coordinates" => json_encode([
            121.52785 + rand(-5, 5) / 1000,
            13.964688 + rand(-5, 5) / 1000,
        ]),
        "location_description" => "Poultry Section",
        "size" => null,
    ],
    [
        "stall_category_id" => 2,
        "name" => "Table 9-Poultry Section",
        "is_occupied" => false,
        "coordinates" => json_encode([
            121.52785 + rand(-5, 5) / 1000,
            13.964688 + rand(-5, 5) / 1000,
        ]),
        "location_description" => "Poultry Section",
        "size" => null,
    ],
    [
        "stall_category_id" => 2,
        "name" => "Table 10-Poultry Section",
        "is_occupied" => false,
        "coordinates" => json_encode([
            121.52785 + rand(-5, 5) / 1000,
            13.964688 + rand(-5, 5) / 1000,
        ]),
        "location_description" => "Poultry Section",
        "size" => null,
    ],
    // Meat
    [
        "stall_category_id" => 3,
        "name" => "Table 1-Meat Section",
        "is_occupied" => false,
        "coordinates" => json_encode([121.52782390109604, 13.965023050206746]),
        "location_description" => "Meat Section",
        "size" => null,
    ],
    [
        "stall_category_id" => 3,
        "name" => "Table 2-Meat Section",
        "is_occupied" => false,
        "coordinates" => json_encode([
            121.52785 + rand(-5, 5) / 1000,
            13.964688 + rand(-5, 5) / 1000,
        ]),
        "location_description" => "Meat Section",
        "size" => null,
    ],
    [
        "stall_category_id" => 3,
        "name" => "Table 3-Meat Section",
        "is_occupied" => false,
        "coordinates" => json_encode([
            121.52785 + rand(-5, 5) / 1000,
            13.964688 + rand(-5, 5) / 1000,
        ]),
        "location_description" => "Meat Section",
        "size" => null,
    ],
    [
        "stall_category_id" => 3,
        "name" => "Table 4-Meat Section",
        "is_occupied" => false,
        "coordinates" => json_encode([
            121.52785 + rand(-5, 5) / 1000,
            13.964688 + rand(-5, 5) / 1000,
        ]),
        "location_description" => "Meat Section",
        "size" => null,
    ],
    [
        "stall_category_id" => 3,
        "name" => "Table 5-Meat Section",
        "is_occupied" => false,
        "coordinates" => json_encode([
            121.52785 + rand(-5, 5) / 1000,
            13.964688 + rand(-5, 5) / 1000,
        ]),
        "location_description" => "Meat Section",
        "size" => null,
    ],
    [
        "stall_category_id" => 3,
        "name" => "Table 6-Meat Section",
        "is_occupied" => false,
        "coordinates" => json_encode([
            121.52785 + rand(-5, 5) / 1000,
            13.964688 + rand(-5, 5) / 1000,
        ]),
        "location_description" => "Meat Section",
        "size" => null,
    ],
    [
        "stall_category_id" => 3,
        "name" => "Table 7-Meat Section",
        "is_occupied" => false,
        "coordinates" => json_encode([
            121.52785 + rand(-5, 5) / 1000,
            13.964688 + rand(-5, 5) / 1000,
        ]),
        "location_description" => "Meat Section",
        "size" => null,
    ],
    [
        "stall_category_id" => 3,
        "name" => "Table 8-Meat Section",
        "is_occupied" => false,
        "coordinates" => json_encode([
            121.52785 + rand(-5, 5) / 1000,
            13.964688 + rand(-5, 5) / 1000,
        ]),
        "location_description" => "Meat Section",
        "size" => null,
    ],
    [
        "stall_category_id" => 3,
        "name" => "Table 9-Meat Section",
        "is_occupied" => false,
        "coordinates" => json_encode([
            121.52785 + rand(-5, 5) / 1000,
            13.964688 + rand(-5, 5) / 1000,
        ]),
        "location_description" => "Meat Section",
        "size" => null,
    ],
    [
        "stall_category_id" => 3,
        "name" => "Table 10-Meat Section",
        "is_occupied" => false,
        "coordinates" => json_encode([
            121.52785 + rand(-5, 5) / 1000,
            13.964688 + rand(-5, 5) / 1000,
        ]),
        "location_description" => "Meat Section",
        "size" => null,
    ],
    // Volante
    [
        "stall_category_id" => 6,
        "name" => "Volante Slot 1",
        "is_occupied" => false,
        "coordinates" => json_encode([121.52785096661347, 13.964688164207226]),
        "location_description" => "Besides Chicken Section",
        "size" => null,
    ],
    [
        "stall_category_id" => 4,
        "name" => "Volante Slot 2",
        "is_occupied" => false,
        "coordinates" => json_encode([121.52782390109604, 13.965023050206746]),
        "location_description" => "Near Entrance",
        "size" => null,
    ],
    [
        "stall_category_id" => 5,
        "name" => "Volante Slot 3",
        "is_occupied" => false,
        "coordinates" => json_encode([121.52767504075022, 13.965141245149185]),
        "location_description" => "Near Meat Section",
        "size" => null,
    ],
];
